#   Checks like this do not really work due to return being a list, evaluation fails with bla.rc == 1
#   Ansible needs modifications to make this work. 
#    - name: Check Walrus Registration
#      action: shell /usr/sbin/euca_conf --list-services | grep -q walrus-${hostvars.{$item}.ansible_hostname}
#      ignore_errors: yes
#      register: walrus_check
#      with_items: ${groups.walrus}
#      tags:
#      - reg

#   - name: Debug
#      action: debug msg="This is return code $walrus_check.x[0].rc"


# TO DO - WORK AROUND THIS BY SETTING A FACT?

    - name: Register Walrus
      action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-walrus --partition walrus --host ${hostvars.{$item}.ansible_$vnet_pub.ipv4.address} --component walrus-${hostvars.{$item}.ansible_hostname}
      with_items: ${groups.walrus}

    - name: Register SC
      action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-sc --partition $partition --host ${hostvars.{$item}.ansible_$vnet_pub.ipv4.address} --component sc-${hostvars.{$item}.ansible_hostname}
      with_items: ${groups.sc}
      tags:
      - reg

    - name: Register CC
      action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-cluster --partition $partition --host ${hostvars.{$item}.ansible_$vnet_pub.ipv4.address} --component cc-${hostvars.{$item}.ansible_hostname}
      with_items: ${groups.cc}
      tags:
      - reg

    - name: Pull cluster (node and cc) keys
      action: fetch src=/var/lib/eucalyptus/keys/{{ partition }}/{{ item }} dest=/tmp/ flat=yes
      with_items:
      - cluster-cert.pem
      - cluster-pk.pem
      - node-cert.pem
      - node-pk.pem

    - name: Get Administrator Credentials
      action: command /usr/sbin/euca_conf --get-credentials /root/admin.zip creates=/root/admin.zip
      tags:
      - creds

    - name: Unpack admin credentials
      action: command /usr/bin/unzip -qou /root/admin.zip -d /root/admin-creds creates=/root/admin-creds/eucarc
      tags:
      - creds

    - name: Source credentials
      action: shell source /root/admin-creds/eucarc && euca-modify-property -p $partition.storage.blockstoragemanager={{ storbackend }}
      tags:
      - storage
                                           
    - name: Configure ELB
      action: yum name=eucalyptus-load-balancer-image state=installed
