    - name: Copy keys to the nodes
      action: copy src=/tmp/${hostvars.${groups.clustercontroller}.ansible_fqdn}/var/lib/eucalyptus/keys/$item dest=/var/lib/eucalyptus/keys/ owner=eucalyptus group=eucalyptus mode=0700
      with_items:
      - cloud-cert.pem
      - cluster-cert.pem
      - node-cert.pem
      - node-pk.pem
      tags:
      - keys

