- name: Stage console instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
    - keypair: lwade
    - instance_type: c1.medium
    - security_group: mongodb
    - image: emi-C1D339FC 

  tasks:
    - name: Launch instance
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true count=5
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=mongos
      with_items: ${ec2.instances}

    - name: Take first instance as primary for configuration of replica set
      local_action: add_host hostname=${ec2.instances[0].public_ip} groupname=mongopri

    - name: Add a generic wait period
      local_action: pause minutes=2

- name: Configure the instance
  hosts: mongos
  user: root
  gather_facts: true

  vars_files:
    - vars/mongodb.yml
    
  tasks:
    - name: Check NTP
      action: service name=ntpd state=started

    - name: Template hosts file
      action: template src=templates/hosts.j2 dest=/etc/hosts
      tags:
        - template

    - name: Copy MongoDB repo file
      action: copy src=files/10gen.repo dest=/etc/yum.repos.d/10gen.repo

    - name: Install packages
      action: yum pkg=$item state=latest
      with_items: 
        - mongo-10gen
        - mongo-10gen-server

    - name: Template the MongoDB configuration file
      action: template src=templates/mongod.conf.j2 dest=/etc/mongod.conf
      
    - name: Prepare the db directory
      action: file path=${db_path} state=directory recurse=yes owner=mongod group=mongod mode=0755

    - name: Configure MongoDB
      action: service name=mongod state=started enabled=yes 
    
- name: Configure the replica set
  hosts: mongopri
  user: root
  gather_facts: true
  
  vars_files:
    - vars/mongodb.yml
    
  tasks: 
    - name: Template the replica set script
      action: template src=templates/replicateset.js.j2 dest=/root/replicaset.js

    - name: Initiate replica set
      action: command mongo /root/replicaset.js
