# This is the task list for setting the common configuration across all Euca components.
# Not all components pick up all options here but that doesn't matter for configuration.
# http://www.eucalyptus.com/docs/3.2/ig/configuring_euca.html#configuring_euca

  - name: Set global network mode 
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_MODE= line=VNET_MODE="\"$network_mode\""
    tags: conf
    notify:
       - restart cloud services 
  
  - name: set NC port
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^NC_PORT line=NC_PORT="\"$nc_port\""
    only_if: is_set('$nc_port')
    tags: conf
    notify:
       - restart cloud services

  - name: set Hypervisor
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^HYPERVISOR= line=HYPERVISOR="\"$hypervisor\""
    only_if: is_set('$hypervisor')
    tags: conf
    notify:
       - restart cloud services

  - name: enable virtio for instance root device
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_ROOT line=USE_VIRTIO_ROOT="\"$use_virtio_root\""
    only_if: is_set('$use_virtio_root')
    tags: conf
    notify:
       - restart cloud services

  - name: enable virtio for instance ebs
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_DISK line=USE_VIRTIO_DISK="\"$use_virtio_disk\""
    only_if: is_set('$use_virtio_disk')
    tags: conf
    notify:
       - restart cloud services

  - name: enable virtio for instance network adapters
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_NET line=USE_VIRTIO_NET="\"$use_virtio_net\""
    only_if: is_set('$use_virtio_net')
    tags: conf
    notify:
       - restart cloud services

  - name: set public interface
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_PUBINTERFACE= line=VNET_PUBINTERFACE="\"$public_iface\""
    only_if: is_set('$public_iface')
    tags: conf
    notify:
       - restart cloud services

  - name: set bridged interface
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_BRIDGE= line=VNET_BRIDGE="\"$bridge\""
    only_if: is_set('$bridge')
    tags: conf
    notify:
       - restart cloud services

  - name: setting log level (applies to CC and NC)
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^LOGLEVEL= line=LOGLEVEL="\"$loglevel\""
    only_if: is_set('$loglevel')
    tags: conf
    notify:
       - restart cloud services

  - name: setting CC port
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^CC_PORT= line=CC_PORT="\"$cc_port\""
    only_if: is_set('$cc_port')
    tags: conf
    notify:
        - restart cloud services

  - name: setting CC scheduling policy
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^SCHEDPOLICY= line=SCHEDPOLICY="\"$schedpolicy\""
    only_if: is_set('$schedpolicy')
    tags: conf
    notify:
       - restart cloud services

  - name: configuring tunnelling 
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^DISABLE_TUNNELING= line=DISABLE_TUNNELING="\"$disable_tunneling\""
    only_if: is_set('$disable_tunneling')
    tags: conf
    notify:
       - restart cloud services

  - name: setting public IP range
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_PUBLICIPS= line=VNET_PUBLICIPS="\"$vnet_publicips\""
    only_if: is_set('$vnet_publicips')
    tags: conf
    notify:
       - restart cloud services

  - name: setting private IP subnet
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_SUBNET= line=VNET_SUBNET="\"$vnet_subnet\""
    only_if: is_set('$vnet_subnet')
    tags: conf
    notify:
       - restart cloud services

  - name: setting private IP subnet netmask
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_NETMASK= line=VNET_NETMASK="\"$vnet_netmask\""
    only_if: is_set('$vnet_netmask')
    tags: conf
    notify:
       - restart cloud services

  - name: setting DNS server
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_DNS= line=VNET_DNS="\"$vnet_dns\""
    only_if: is_set('$vnet_dns')
    tags: conf
    notify:
       - restart cloud services

  - name: setting number of simultaneous instances per security group
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_ADDRSPERNET= line=VNET_ADDRSPERNET="\"$vnet_addrspernet\""
    only_if: is_set('$vnet_addrspernet')
    tags: conf
    notify:
       - restart cloud services

  - name: setting local IP for CLC and CC
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_LOCALIP= line=VNET_LOCALIP="\"$vnet_localip\""
    only_if: is_set('$vnet_localip')
    tags: conf
    notify:
       - restart cloud services

  - name: setting NC-facing network device
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_PRIVINTERFACE= line=VNET_PRIVINTERFACE="\"$vnet_pri\""
    only_if: is_set('$vnet_pri')
    tags: conf
    notify:
       - restart cloud services

  - name: setting public-facing network device
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_PUBINTERFACE= line=VNET_PUBINTERFACE="\"$vnet_pub\""
    only_if: is_set('$vnet_pub')
    tags: conf
    notify:
       - restart cloud services
