  - name: registering nodes
    action: euca_conf --no-scp --no-rsync --no-sync --register-nodes="${item.ansible_${public_iface}.ipv4.address}"
    with_items: ${groups.nc}

  - name: fetch the keys for a copy
    action: fetch src=/var/lib/eucalyptus/keys/$item dest=/root/$item
    with_items: 
        - cloud-cert.pem
        - cluster-cert.pem
        - node-cert.pem
        - node-pk.pem

  - name: copy the keys to the node
    action: copy src=/root/$item dest=/var/lib/eucalyptus/keys/$item owner=eucalyptus group=eucalyptus mode=0700
    with_items:
        - cloud-cert.pem
        - cluster-cert.pem
        - node-cert.pem
        - node-pk.pem
