# ----------------------------------------------------- 
# This playbook is an example for deploying a single Eucalyptus user console instance into EC2/Euca
# -----------------------------------------------------

- name: Stage console instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: lwade
      instance_type: c1.medium
      security_group: default
      image: emi-C1D339FC 

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true 
      register: ec2
     
    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched 
      with_items: ${ec2.instances}

    - name: Wait for SSH to come up
      local_action: wait_for host=${item.public_dns_name} port=22 delay=60 timeout=320 state=started
      with_items: ${ec2.instances}

- name: Configure instance
  hosts: launched
  user: root
  gather_facts: True

  vars_files:
      - vars/euca-console.yml
     
  handlers:
    - name: restart console
      action: service name=eucalyptus-console state=restarted
 
  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started
   
    - name: Downloads the repo RPMs
      action: get_url url=$item dest=/tmp/ thirsty=yes
      with_items:
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
      tags:
      - geturl

    - name: Install the repo RPMs
      action: command rpm -Uvh --force /tmp/$item
      with_items:
      - eucalyptus-release-${euca_version}.noarch.rpm
      - epel-release-6.noarch.rpm
      - elrepo-release-6.noarch.rpm
 
    - name: Install Eucalyptus User Console
      action: yum pkg=eucalyptus-console-${console_version} state=latest
      notify:
      - restart console 

    - name: Template the User Console Configuration with VMtype Definition
      action: template src=templates/console.ini.j2 dest=/etc/eucalyptus-console/console.ini 
      only_if: euca_version|int == 3.2
      notify:
      - restart console

    - name: Debug
      action: debug msg="This is {{ euca_version }} here"

