# ----------------------------------------------------- 
# This playbook is an example for deploying a single Eucalyptus user console instance into EC2/Euca
# -----------------------------------------------------

- name: Stage console instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: admin
      instance_type: m1.small
      security_group: default
      image: emi-048B3A37

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true 
      register: ec2
     
    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched 
      with_items: ${ec2.instances}

- name: Configure instance
  hosts: launched
  user: root
  gather_facts: True

  vars_files:
      - vars/euca-console.yml
     
  handlers:
    - name: restart console
      action: service name=eucalyptus-console state=restarted
 
  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started
   
    - name: Downloads the repo RPMs
      action: get_url url=$item dest=/tmp/ thirsty=yes
      with_items:
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
      - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
      tags:
      - geturl

    - name: Install the repo RPMs
      action: command rpm -Uvh --force /tmp/$item
      with_items:
      - eucalyptus-release-${euca_version}.noarch.rpm
      - epel-release-6.noarch.rpm
      - elrepo-release-6.noarch.rpm
 
    - name: Install Eucalyptus User Console
      action: yum pkg=eucalyptus-console state=latest
      notify:
      - restart console 

    - name: Configure User Console Endpoint
      action: lineinfile dest=/etc/eucalyptus-console/console.ini state=present regexp=^clchost line=clchost:" ${clchost}"
      notify:
      - restart console

    - name: Configure User Console Port
      action: lineinfile dest=/etc/eucalyptus-console/console.ini state=present regexp=^uiport line=uiport:" ${port}"
      notify:
      - restart console

    - name: Configure User Console Language
      action: lineinfile dest=/etc/eucalyptus-console/console.ini state=present regexp=^language line=language:" ${lang}"
      notify:
      - restart console
