# Playbook for the cloud deployment. Ordering is important as a deployment is sequential. 

- hosts: cc
  tasks:
    - name: setup
      action: setup

- hosts: nc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - nc
  post_tasks:
    - action: setup

- hosts: cc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - cc
    
- hosts: sc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - sc

- hosts: walrus
  vars_files:
    - vars/main.yml
  roles:
    - common
    - walrus
 
- hosts: clc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - clc

- hosts: walrus
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/walrus/tasks/walrus-keys.yml

- hosts: sc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/sc/tasks/sc-keys.yml

- hosts: clc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/clc/tasks/component-reg.yml

- hosts: cc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/cc/tasks/cluster-reg.yml 
  
- hosts: nc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/nc/tasks/nc-keys.yml 
