#  - name: Import RPM keys
#    action: rpm_key state=present key={{ item }} 
#    with_items: keys
  
  - name: Template repo files (release)
    action: template src={{ item }}.j2 dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - eucalyptus-release.repo
    - euca2ools-release.repo
    - elrepo.repo
    - epel.repo
    when: not nightlies 

  - name: Template repo files (nightly)
    action: template src={{ item }}.j2 dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - eucalyptus-nightly.repo
    - euca2ools-release.repo
    - elrepo.repo
    - epel.repo
    when: nightlies
  
  - name: Install packages
    action: yum name={{ item }} state=installed enablerepo=base,updates
    with_items:
    - libselinux-python
    - tuned
    - unzip
    - ntp
    tags:
    - packages

  - name: Fix java version
    action: yum name=http://mirror.centos.org/centos/6.4/updates/x86_64/Packages/java-1.7.0-openjdk-1.7.0.25-2.3.10.4.el6_4.x86_64.rpm state=installed enablerepo=base,updates
   
  - name: Ensure SELinux is disabled
    action: selinux policy=targeted state=permissive
   
  - name: Turn on NTP and start on boot
    action: service name=ntpd enabled=yes state=started
    tags:
    - ntp

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags:
    - firewall
